# Generated by Django 4.2.3 on 2023-08-17 04:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default/account.png', null=True, upload_to=accounts.models.get_upload_path),
        ),
    ]
