# Generated by Django 4.0.10 on 2023-04-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_securequsans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='secureQusAns',
            field=models.CharField(blank=True, default=None, max_length=255),
            preserve_default=False,
        ),
    ]
